# Generated by Django 3.0.4 on 2020-03-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0006_increase_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('code', models.CharField(db_index=True, max_length=3, verbose_name='code')),
                ('name', models.CharField(db_index=True, max_length=55, verbose_name='name')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=4, verbose_name='symbol')),
                ('factor', models.DecimalField(decimal_places=10, default=1.0, help_text='Specifies the currency rate ratio to the base currency.', max_digits=30, verbose_name='factor')),
                ('is_active', models.BooleanField(default=True, help_text='The currency will be available.', verbose_name='active')),
                ('is_base', models.BooleanField(default=False, help_text='Make this the base currency against which rate factors are calculated.', verbose_name='base')),
                ('is_default', models.BooleanField(default=False, help_text='Make this the default user currency.', verbose_name='default')),
                ('info', jsonfield.fields.JSONField(blank=True, default={})),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical currency',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
